services:

  db:
    image: percona
    environment:
      MYSQL_ROOT_PASSWORD: letmein
      MYSQL_DATABASE: employeemanager
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 9000:8080